package microservices.booking.dto;

public enum Grooming {
    SMALL_DOG_GROOM_CUT(89),
    SMALL_DOG_WASH_GROOM(140),
    SMALL_DOG_WASH_GROOM_CUT(190),
    SMALL_DOG_DE_SHED(59),
    SMALL_DOG_EAR_CLEAN(29),
    SMALL_DOG_NAIL_TRIM(36),
    SMALL_DOG_HOTSPOTS(29),
    MEDIUM_DOG_GROOM_CUT(99),
    MEDIUM_DOG_WASH_GROOM(175),
    MEDIUM_DOG_WASH_GROOM_CUT(235),
    MEDIUM_DOG_DE_SHED(75),
    MEDIUM_DOG_EAR_CLEAN(42),
    MEDIUM_DOG_NAIL_TRIM(47),
    MEDIUM_DOG_HOTSPOTS(39),
    LARGE_DOG_GROOM_CUT(118),
    LARGE_DOG_WASH_GROOM(205),
    LARGE_DOG_WASH_GROOM_CUT(275),
    LARGE_DOG_DE_SHED(80),
    LARGE_DOG_EAR_CLEAN(52),
    LARGE_DOG_NAIL_TRIM(60),
    LARGE_DOG_HOTSPOTS(52),
    GIANT_DOG_GROOM_CUT(142),
    GIANT_DOG_WASH_GROOM(245),
    GIANT_DOG_WASH_GROOM_CUT(305),
    GIANT_DOG_DE_SHED(83),
    GIANT_DOG_EAR_CLEAN(64),
    GIANT_DOG_NAIL_TRIM(66),
    GIANT_DOG_HOTSPOTS(64),
    DOG_TEETH_CLEAN(48),
    CAT_GROOM_CUT(168),
    CAT_WASH_GROOM(168),
    CAT_WASH_GROOM_CUT(210),
    CAT_DE_SHED(34),
    CAT_EAR_CLEAN(31),
    CAT_NAIL_TRIM(44),
    CAT_HOTSPOTS(31),
    CAT_TEETH_CLEAN(46);

    private float price;

    Grooming(float price) {
        this.price = price;
    }

    public float getPrice() {
        return price;
    }
}
